src/cli.py, src/core.py, src/templates/table/publish.sql, src/templates/table/table_config.yaml, tests/test_storage.py, tests/test_table.py
=> Add tests to table/storage classes and table is now a view

pytest.ini, src/configs/templates/table/publish.sql, src/core.py, tests/sample_data/table/publish.sql, tests/sample_data/table/publish_part.sql, tests/test_dataset.py, tests/test_table.py
=> Staging name in table

src/base.py, src/cli.py, src/storage.py, src/table.py
=> Cria table create

basedosdados/base.py
Fix the creation of template folder
=> fix template folder creation

bases/br_tse_eleicoes/detalhes_votacao_municipio_zona/table_config.yaml
=> Fixes table_config.

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/bugs.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/language-request.md, .github/ISSUE_TEMPLATE/new_data.md, .github/ISSUE_TEMPLATE/nova-linguagem.md, .github/ISSUE_TEMPLATE/novas-funcionalidades.md, .github/ISSUE_TEMPLATE/novos-dados.md, .github/ISSUE_TEMPLATE/version-request.md
Adiciona templates de issues para facilitar nossas vidas
=> Update issue templates

basedosdados/base.py, bases/br_cgu_servidores_executivo_federal/README.md, bases/br_cgu_servidores_executivo_federal/dataset_config.yaml
Este merge apenas cria a dataset de dados de servidores do executivo federal, obtidos do Portal da Transparência (config e readme preenchidos).
=> Add cgu servidores dataset

docs/naming_rules.md
Correção menor de um parêntese que estava trocado no texto
=> Correção de parêntese trocado

bases/br_ibge_populacao/municipios/table_config.yaml
No ano=2000 apontado no issue #230.
=> Conserta erro em dados de população municipal.

basedosdados/base.py
Fix #237. Fix the conversion of metadata_path to lower
=> fix the conversion of metadata_path to lower

basedosdados/configs/templates/table/publish.sql, basedosdados/table.py
Fix #236. Essa alteração só resolve no caso em que o staging é o mesmo que o prod, tem que inserir dois project_id diferentes, um pra prod onde é criado a view e outro do stating onde está a tabela
=> resolve bug do project_id no publish.sql

basedosdados/cli.py, basedosdados/table.py
=> Prepare basedosdados to Propose Action

basedosdados/configs/templates/table/table_config.yaml, basedosdados/table.py
Adiciona nome do bucket ao table_config
=> add new metadata fields to table_config template

basedosdados/storage.py, basedosdados/table.py
fix tab bug in table create and remove print from copy and delete blobs
=> fix tab bug in table create and remove print from copy and delete blobs

docs/colab_data.md
Aprimorando a descricao sobre como subir os dados ;)
=> [docs] update colab_data.md

basedosdados/cli.py
Tinha um erro meu no if_table_config_exists no CLI, que não tava pasando o argumento para a chamada da função.
=> [infra]CLI table create fix

bases/br_ibge_ppm/efetivo_rebanhos/table_config.yaml, bases/br_ibge_ppm/producao_aquicultura/table_config.yaml, bases/br_ibge_ppm/producao_origem_animal/table_config.yaml, bases/br_ibge_ppm/producao_pecuaria/table_config.yaml
add new fields 
source_bucket_name: basedosdados-dev
project_id_staging: basedosdados-dev
project_id_prod: basedosdados-dev
=> [dados] br_ibge_ppm add new fields

bases/br_cgu_servidores_executivo_federal/code/README.md, bases/br_cgu_servidores_executivo_federal/code/requirements.txt, bases/br_cgu_servidores_executivo_federal/code/servidores.py
Inclui código de ETL para os dados de servidores do executivo federal do Portal da Transparência.
=> [dados] br_cgu_servidores_executivo_federal

.github/workflows/table-approve.yml, bases/br_bd_diretorios_brasil/dataset_config.yaml, bases/br_bd_diretorios_brasil/escola/table_config.yaml
=> [dados] br_bd_diretorios_brasil | fix create

python-package/basedosdados/cli.py, python-package/basedosdados/storage.py
- Adiciona `storage` `download` ao CLI
- Tira o argumento partitioned do `table` `create`
- Corrige a docstring da `Storage.download`
=> [infra] Update CLI

python-package/basedosdados/cli.py
=> [infra] fix table_id order in CLI table append

.github/workflows/build-docs.yml, .github/workflows/deploy-docs.yml, .github/workflows/docs.yml, Makefile, docs/access_data_local.md, docs/reference_api_cli.md, docs/reference_api_py.md, docs/reference_api_r.md, mkdocs.yml, python-package/basedosdados/__init__.py, python-package/basedosdados/cli/cli.py, python-package/basedosdados/download/download.py, python-package/basedosdados/upload/storage.py, python-package/basedosdados/upload/table.py
Closes #350 .
Adicional:
- Resolve paths com a nova configuração das pastas
- Correções nas docstrings do pacote Python
@pedrocava sabe algum jeito de deixar a documentação automatizada no corpo do site? Por enquanto só deixei o embed do PDF online mesmo... Parece ter algo aqui que podemos fazer com Actions: https://compbiocore.github.io/cbc-documentation-templates/mkdocs/#documentation-structure-for-r-packages
=> [docs] Atualiza documentação com o pacote em R

LICENSE
Nós não temos LICENSE do projeto :0
Podemos colocar a MIT por enquanto, mas está aberto a discussão
=> [infra] Create LICENSE

docs/colab_data.md, python-package/basedosdados/cli/cli.py, python-package/basedosdados/download/download.py, python-package/basedosdados/upload/base.py, python-package/basedosdados/upload/dataset.py, python-package/basedosdados/upload/datatypes.py, python-package/basedosdados/upload/storage.py, python-package/pyproject.toml
- #512 
1. Adiciona novo comando no CLI, `basedosdados config init` para inicializar o config
2. Se o `project_id` do `staging` for o mesmo do `prod`, então automaticamente copia o `staging.json >> prod.json`
3. Muda versão para `1.5.4`
=> [infra] Melhora inicialização do CLI

.github/workflows/data-check/checks.yaml, .github/workflows/data-check/test_data.py
Corrige o issue #507. Ainda vou testar a action.
=> [infra] fix primary key test logic

README.md, docs/access_data_bq.md, docs/access_data_local.md, docs/support.md
=> [docs] Muda municipios para municipio em PIB e população.

python-package/basedosdados/upload/table.py
Descrição:
Corrige issue #555 adicionando uma função `table_exists` que retorna `True` ou `False`  e implementa a mesma no `Table.append()` para evitar recriar a tabela.
Changelog:
- Adiciona `table_exists()` ao `table.py`
- Implementa `table_exists()` e refatora o `Table.append()`
=> [infra] Adiciona check para existência da tabela

bases/br_ms_vacinacao_covid19/microdados_estabelecimento/table_config.yaml, bases/br_ms_vacinacao_covid19/microdados_paciente/table_config.yaml, bases/br_ms_vacinacao_covid19/microdados_vacinacao/table_config.yaml
=> [dados-bot] br_ms_vacinacao_covid19 (2021-07-07)

bases/br_ms_vacinacao_covid19/microdados_estabelecimento/table_config.yaml, bases/br_ms_vacinacao_covid19/microdados_paciente/table_config.yaml, bases/br_ms_vacinacao_covid19/microdados_vacinacao/table_config.yaml
O microdados vem em outro PR por ser a primeira tabela deles
=> [dados-bot] br_ms_vacinacao_covid19 (2021-07-09)

docs/colab_checks.md, docs/colab_data.md, docs/colab_infrastructure.md, docs/odd_2021.md, docs/style_data.md, r-package/R/zzzz.R
=> [docs] atualiza links do discord

extras/revisao_bases/mapeando_erros_tipagem_bd.ipynb
Adiciona uma nova pasta com arquivos extras a Base dos Dados, com o código que mapeia os erros e gera tabelas que contém tais erros.
=> [extra-revisao] add codigo mapeamento erros tipagem

bases/br_ms_vacinacao_covid19/microdados/table_config.yaml, bases/br_ms_vacinacao_covid19/microdados_estabelecimento/table_config.yaml, bases/br_ms_vacinacao_covid19/microdados_paciente/table_config.yaml, bases/br_ms_vacinacao_covid19/microdados_vacinacao/table_config.yaml
=> [dados-bot] br_ms_vacinacao_covid19 (2021-07-28)

python-package/basedosdados/download/download.py, python-package/basedosdados/exceptions.py, python-package/basedosdados/upload/table.py, python-package/basedosdados/validation/exceptions.py, python-package/tests/test_download.py, python-package/tests/test_table.py
Novo release v1.5.6
CHANGELOG:
-  #626
=> [infra] v.1.5.6

bases/br_ms_vacinacao_covid19/microdados/table_config.yaml, bases/br_ms_vacinacao_covid19/microdados_estabelecimento/table_config.yaml, bases/br_ms_vacinacao_covid19/microdados_paciente/table_config.yaml, bases/br_ms_vacinacao_covid19/microdados_vacinacao/table_config.yaml
Sobe dados Vacinação
max dia de vacinação 15-08 - 18/08
=> [dados-bot] br_ms_vacinacao_covid19 (2021-08-19)

bases/br_ms_vacinacao_covid19/microdados/table_config.yaml, bases/br_ms_vacinacao_covid19/microdados_estabelecimento/table_config.yaml, bases/br_ms_vacinacao_covid19/microdados_paciente/table_config.yaml, bases/br_ms_vacinacao_covid19/microdados_vacinacao/table_config.yaml
Última data de aplicação da vacina : 20/ 08 - 21/08
=> [dados-bot] br_ms_vacinacao_covid19 (2021-08-22)

bases/br_ms_vacinacao_covid19/microdados/table_config.yaml, bases/br_ms_vacinacao_covid19/microdados_estabelecimento/table_config.yaml, bases/br_ms_vacinacao_covid19/microdados_paciente/table_config.yaml, bases/br_ms_vacinacao_covid19/microdados_vacinacao/table_config.yaml
últimas datas de vacinação: 20/08 a 22/08
=> [dados-bot] br_ms_vacinacao_covid19 (2021-08-23)

bases/br_ms_vacinacao_covid19/microdados/table_config.yaml, bases/br_ms_vacinacao_covid19/microdados_estabelecimento/table_config.yaml, bases/br_ms_vacinacao_covid19/microdados_paciente/table_config.yaml, bases/br_ms_vacinacao_covid19/microdados_vacinacao/table_config.yaml
Dados atualizados. Últimas datas de vacinação 27/08 a 28/08
=> [dados-bot] br_ms_vacinacao_covid19 (2021-08-29)

.github/workflows/data-check.yml, .github/workflows/data-check/checks.yaml, .github/workflows/data-check/conftest.py, .github/workflows/data-check/test_data.py, .github/workflows/table-approve.yml, bases/br_bd_diretorios_brasil/escola/table_config.yaml, bases/br_sp_alesp/deputado/table_config.yaml
Vou deixar essa parte para outro PR
=> [infra] corrige o `data-check` em pull requests

bases/br_ms_vacinacao_covid19/microdados/table_config.yaml, bases/br_ms_vacinacao_covid19/microdados_estabelecimento/table_config.yaml, bases/br_ms_vacinacao_covid19/microdados_paciente/table_config.yaml, bases/br_ms_vacinacao_covid19/microdados_vacinacao/table_config.yaml
Max. datas de vacinação(UF) 05-09 a 06-09
=> [dados-bot] br_ms_vacinacao_covid19 (2021-09-07)

bases/br_anatel_telefonia_movel/ddd/publish.sql, bases/br_anatel_telefonia_movel/ddd/table_config.yaml, bases/br_anatel_telefonia_movel/ddd/table_description.txt, bases/br_anatel_telefonia_movel/modalidade/publish.sql, bases/br_anatel_telefonia_movel/modalidade/table_config.yaml, bases/br_anatel_telefonia_movel/modalidade/table_description.txt, bases/br_anatel_telefonia_movel/municipio/publish.sql, bases/br_anatel_telefonia_movel/municipio/table_config.yaml, bases/br_anatel_telefonia_movel/municipio/table_description.txt, bases/br_anatel_telefonia_movel/tecnologia/publish.sql, bases/br_anatel_telefonia_movel/tecnologia/table_config.yaml, bases/br_anatel_telefonia_movel/tecnologia/table_description.txt
=> [dados-atualizacao] br_anatel_telefonia_movel

bases/br_ms_vacinacao_covid19/dicionario/table_config.yaml
Atualização dicionário vacinação
=> [dados] br_ms_vacinacao_covid19

bases/br_geobr_mapas/setor_censitario_2010/publish.sql
Alterei algumas colunas no `publish.sql` da tabela `br_geobr_mapas.setor_censitario_2010`. 
O mais indicado é consertar isso direto nos dados que estão no [storage](https://console.cloud.google.com/storage/browser/basedosdados-dev/staging/br_geobr_mapas/setor_censitario_2010?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&project=basedosdados-dev&prefix=&forceOnObjectsSortingFiltering=false).
Lembrar de mudar o `publish.sql` depois de subir os dados tratados
=> [dados] Fix/br geobr mapas columns types

docs/access_data_packages.md
closes #973 #945 #931 #916 #895
=> [docs] corrije link quebrado

README.md, docs/access_data_packages.md, mkdocs.yml, python-package/requirements-dev.txt
Esse PR é uma tentativa de consertar a documentação através da reversão das mudanças do arquivo `mkdocs.yml` provenientes do merge da `python-1.6.0`.
=> [docs] Reverte mudanças em `mkdocs.yml` causadas pelo merge do Python 1.6.0

bases/br_ibge_pnadc/ano_brasil_grupo_idade/table_config.yaml, bases/br_ibge_pnadc/ano_brasil_raca_cor/table_config.yaml, bases/br_ibge_pnadc/ano_municipio_grupo_idade/table_config.yaml, bases/br_ibge_pnadc/ano_municipio_raca_cor/table_config.yaml, bases/br_ibge_pnadc/ano_regiao_grupo_idade/table_config.yaml, bases/br_ibge_pnadc/ano_regiao_metropolitana_grupo_idade/table_config.yaml, bases/br_ibge_pnadc/ano_regiao_metropolitana_raca_cor/table_config.yaml, bases/br_ibge_pnadc/ano_regiao_raca_cor/table_config.yaml, bases/br_ibge_pnadc/ano_uf_grupo_idade/table_config.yaml, bases/br_ibge_pnadc/ano_uf_raca_cor/table_config.yaml
sobe com metadata_modified alterado
=> [dados] br_ibge_pnad.populacao

bases/br_ms_vacinacao_covid19/microdados/table_config.yaml, bases/br_ms_vacinacao_covid19/microdados_estabelecimento/table_config.yaml, bases/br_ms_vacinacao_covid19/microdados_paciente/table_config.yaml, bases/br_ms_vacinacao_covid19/microdados_vacinacao/table_config.yaml
=> [dados-bot] br_ms_vacinacao_covid19 (2022-01-15)

bases/br_ms_vacinacao_covid19/microdados/table_config.yaml, bases/br_ms_vacinacao_covid19/microdados_estabelecimento/table_config.yaml, bases/br_ms_vacinacao_covid19/microdados_paciente/table_config.yaml, bases/br_ms_vacinacao_covid19/microdados_vacinacao/table_config.yaml
Sobe os dados, exclusive SP porque o [link](https://d26692udehoye.cloudfront.net/SIPNI/COVID/particionado/uf%3DSP/part-00000-3293cae9-79d1-43ec-b42c-ad2a6630f03c.c000.csv) tá quebrado :/
=> [dados-bot] br_ms_vacinacao_covid19 (2022-01-23)

docs/colab_data.md
Alterações feitas com base na proposta do @mfagundes
=> [docs] faz alterações na documentação colaboradores

.github/workflows/data-check.yml, .github/workflows/metadata-validate.yml, .github/workflows/table-approve.yml, README.md, python-package/basedosdados/__init__.py, python-package/basedosdados/constants.py, python-package/basedosdados/download/download.py, python-package/basedosdados/download/metadata.py, python-package/basedosdados/upload/base.py, python-package/basedosdados/upload/table.py, python-package/pyproject.toml, python-package/tests/test_download/test_metadata.py
`pip install basedosdados-1.6.3b2`
- Conserta `table.update` para o modo staging
- Adiciona loguro no poetry
- Remove parâmetro querry das funções `bd.funcoes list_datasets` e `bd.list_dataset_table`
- Conserta configuração de variáveis globais no `constatns.config`
- Adiciona parâmetro `from_file` ao `constatns.config`
Neste PR faço os ajustes necessários nas funções list_datasets e list_dataset_table. A list_datasets agora não precisa mais do argumento query e a list_dataset_table retorna exclusivamente recursos do tipo bdm_table. Os testes também foram alterados, quando pertinente.
=> [infra] python-v1.6.3

python-package/basedosdados/upload/table.py, python-package/pyproject.toml
`pip install basedosdados==1.6.5b1`
- Ajusta função `_is_partitioned` pare retornar false caso a lista de partições seja vazia
=> [infra] fix/is_partitioned 

python-package/basedosdados/download/base.py
autenticação usando o google auth para teste no colab
=> authentication using google auth

python-package/basedosdados/download/base.py, python-package/pyproject.toml
=> Colab authentication

python-package/basedosdados/download/base.py, python-package/pyproject.toml
Autenticação no colab, retornando o PyData para autenticação local
=> authentication with colab or PyData

docs/api_reference_r.md
altera e contribuí para a documentação do pacote basedosdados no Rstudio
=> [dados] update_doc_r

bases/br_inep_sinopse_estatistica_educacao_basica/dicionario/table_config.yaml, bases/br_inep_sinopse_estatistica_educacao_basica/municipio_matricula_localizacao_rede/table_config.yaml
Tabelas `dicionario` e `municipio_matricula_localizacao_rede`
=> br_inep_sinopse_estatistica_educacao_basica

bases/br_inpe_prodes/desmatamento_municipio/publish.sql
sobe alteração do table_publish
=> [dados-update] br_inpe_prodes

bases/br_inep_sinopse_estatistica_educacao_basica/dicionario/table_config.yaml
=> br_inep_sinopse_estatistica_educacao_basica.dicionario

python-package/pyproject.toml
Simplify and amplify dependencies.
No need for jupyter and mkdocs deps. Unlock pandas version
=> [infra] Simplify and amplify dependencies

bases/br_isp_estatisticas_seguranca/taxa_evolucao_mensal_municipio/table_config.yaml
Arrumando os metadados da `br_isp_estatisticas_seguranca.taxa_evolucao_mensal_municipio`
=> [dados-atualziacao ] fix metadata`br_isp_estatisticas_seguranca.taxa_evolucao_mensal_municipio`

bases/br_mobilidados_indicadores/comprometimento_renda_tarifa_transp_publico/table_config.yaml
=> [dados-atualizacao] fix metadata `br_mobilidados_indicadores.comprometimento_renda_tarifa_transp_publico`

python-package/pyproject.toml
- updating pandas version
- removing unused dependencies
=> bump version 1.6.9

bases/br_sgp_informacao/code/cartao_corporativo.R, bases/br_sgp_informacao/despesas_cartao_corporativo/table_config.yaml
=> [dados-atualizacao] fix encoding `br_sgp_informacao.despesas_cartao_corporativo`

r-package/DESCRIPTION
O CRAN escreveu pedindo para a gente consertar a exibição da URL
=> Atualiza a exibição da URL na descrição do pacote de R

bases/br_ibge_pib/code/build.do
Já subi os dados consertados pra prod via storage.
=> [dados] fix `br_ibge_pib.municipio` table

docs/index.md
=> [doc] update_texto_download

docs/colab_data.md
Principais mudanças:
- Reduziu de 10 para 8 passos
- Coloquei um resumo do processo antes de começar os passos
- Ajustei links da pasta `mais` para `queries-basedosdados` 
- Na etapa de arquitetura criei um passo a passo para deixar o processo mais linear
- Ajustei a parte de subir os dados pra Cloud para o pacote e fluxo novo
- Ajustei a parte de abrir PR para o repo novo 
- A parte de preenchimento de metadados tá só com a equipe dados por enquanto
closes #1672
=> [fix] data_colab

python-package/basedosdados/__init__.py, python-package/basedosdados/constants.py, python-package/basedosdados/download/base.py, python-package/basedosdados/download/download.py, python-package/basedosdados/download/metadata.py, python-package/basedosdados/exceptions.py, python-package/basedosdados/upload/base.py, python-package/basedosdados/upload/connection.py, python-package/basedosdados/upload/dataset.py, python-package/basedosdados/upload/datatypes.py, python-package/basedosdados/upload/storage.py, python-package/basedosdados/upload/table.py, python-package/basedosdados/upload/utils.py, python-package/tests/conftest.py, python-package/tests/test_base.py, python-package/tests/test_dataset.py, python-package/tests/test_datatype.py, python-package/tests/test_metadata.py, python-package/tests/test_metadata_api/test_metadata_api.py, python-package/tests/test_metadata_api/test_publish.py, python-package/tests/test_storage.py, python-package/tests/test_table.py, python-package/tests/test_utils.py
=> chore: remove pylint comments

.github/workflows/deploy-docs.yml
Fix the Github Action workflow. Now if any file inside docs change will fire the deploy.
Is only possible to test pushing to main.
=> chore: update deploy-docs.yml to include all files in the docs directory

.github/workflows/deploy-docs.yml, docs/docs/access_data_packages.md
=> fix: update deploy-docs.yml

docs/docs/colab_data.md
Remoção de acentos, letras maiúsculas e listagem dos referenciadores.
=> [fix] Consertar e listar referencia para os topicos

.github/workflows/deploy-docs.yml
Bump python version to 3.10, 3.7 is too old
=> Fix deploy-docs workflow

.github/workflows/ci-python.yml, .github/workflows/deploy-docs.yml
Poetry v2 has been released and has breaking changes
=> CI: pin poetry version

.gitignore, python-package/tests/test_upload/test_dataset.py, python-package/tests/test_upload/test_datatype.py, python-package/tests/test_upload/test_storage.py, python-package/tests/test_upload/test_table.py
Ajustes nos testes de upload do pacote python e também adicionado dois paths referentes no gitignore
Comentários resolvidos do PR: https://github.com/basedosdados/sdk/pull/1753
=> Ajustes nos testes e complemento no .gitgnore

python-package/pyproject.toml, python-package/setup.py
=> python-package: release v2.0.2

python-package/basedosdados/backend.py
```
uv run python
```
```
Python 3.9.20 (main, Oct  2 2024, 16:35:48)
[Clang 18.1.8 ] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import basedosdados as bd
>>> backend = bd.Backend(graphql_url="my_url")
>>> backend.graphql_url
'my_url'
>>> backend_2 = bd.Backend(graphql_url="my_second_url")
>>> backend.graphql_url
'my_url'
>>> backend_2.graphql_url
'my_second_url'
```
Close #1776
=> python-package: fix `Backend` class
