basedosdados/sdk

- basedosdados/base.py
Prior to this fix, an / operator was applied between two strings if a custom path to metadata folder was provided. This operation should use a PosixPath to create a path. I fixed this by turning the string that represents the custom path into a PosixPath.
> Small bug fix on custom path to databases metadata folder

- basedosdados/cli.py
- docs/cli_reference_api.md
- mkdocs.yml
- requirements-dev.txt
Usando `mkdocs-click` 🙂 
Não é tão bonito visualmente quanto o `mkdocstrings` - este último só tem `handler` para Python por enquanto.
TODO:
- Adicionar docstrings nos comandos gerais do CLI:
- `cli`
- `config`
- `download`
- `dataset`
- `storage`
- `table` --> o que faz exatamente o `update` aqui, sobrescreve numa tabela já existente? não seria o mesmo de `publish --if_exists replace`?
> Adiciona documentação do CLI

- basedosdados/storage.py
- basedosdados/table.py
- pyproject.toml
Um fix simples para esse problema de paths seria usar o pathlib.Path.as_posix() 
no trecho do código em que se dá parse nas partições. 
Visto que o problema está na manipulação de strings e não realmente na hora de se fazer
uma chamada no caminho real do arquivo.
Tentei alguns jeitos diferentes, porém a mudança para métodos do ### os acaba deixando o código mais poluído e menos legivel.
> [infra] Corrige issue #267: 

- basedosdados/cli.py
Corrigindo um contexto que estava sendo passado errado no table init do CLI
> [infra]Minor fix no table init do CLI

- basedosdados/cli.py
- docs/cli_reference_api.md
Adiciona os seguintes comandos:
basedosdados list 
datasets --filter_by --with_description
dataset_tables <dataset_id> --filter_by --with_description
basedosdados get
dataset_description <dataset_id>
table_description <dataset_id> <table_id>
table_columns <dataset_id> <table_id>
Todos tem como opção --project_id deixado com "basedosdados" por default.
*********Estão funcionais, aparentemente não precisou da autorização que tava pedindo antes, pode ser algum problema com as minhas configs*********
> [infra] Add metadata functions to CLI

- basedosdados/table.py
#276 
Como se publica VIEWS, é possível que ao fazer o update da table, a query da VIEW não tenha terminado ainda. A idéia é forçar a query terminar antes de prosseguir com o update da table.
Baseado na [referencia](https://googleapis.dev/python/bigquery/latest/index.html) do google (Na seção "Example Usage"), o a função `result()` de um job de query espera o resultado da query terminar.
> [infra] In function publish, forced query to complete before updating table

- r-package/DESCRIPTION
A issue #411 apresenta uma usuária em que provavelmente a versao do readr que ela possui instalada causa um erro. Para evitar esse tipo de problema com dependencias, a boa prática da comunidade é adicionar a versao mínima dos packages. Entende-se como versao mínima, a versao das dependências quais foram utilizadas no momento do desenvolvimento.
O que o pull request faz é adicionar uma versao mínima para a `readr`, o que fará o `R` atualizar a dependencia caso a instalada no computador do usuário seja menor que a mínima necessária.  Deixo como recomendaçao aos desenvolvedores adicionar a versao mínima em todos as bibliotecas.
Mais informaçoes podem ser encontradas na [seçao 8.1.1 do livro R-Packages](https://r-pkgs.org/description.html), lá Wickham e Bryan, dizem:
> Versioning is most …
> Versao minima da dependencia readr.

- .gitignore
As pastas `input`, `output` e `tmp` dentro de `bases` não são enviadas para o repo, fazem parte do processo de limpeza, no entanto são trackeadas pelo git.
Essa PR adiciona as três no gitignore.
> [infra] update gitignore

- python-package/tests/test_download.py
- python-package/tests/test_storage.py
- python-package/tests/test_table.py
Changelog:
- Conserta a o nome da tabela na query defaul de `municipios` para `municipio` devido padronização de dados no datalake
- Modificação para uso de Path explicito, utilizando o Path do arquivo que está sendo executado
> [infra] fix default query and path mess in CI

- python-package/basedosdados/download/download.py
- python-package/tests/test_download.py
- python-package/tests/test_storage.py
* #522 
1. Adiciona parâmetro `output_type` às funções `list_datasets` e `list_dataset_tables` da API do Python. O `output_type` admite apenas as opções `"list"` ou `"print"`, de forma excludente, sendo `"print"` o valor padrão.
2. Adiciona teste simples para cada uma das duas funções, para o caso do `output_type="list"`, já que a opção `"print"` já está coberta pelos testes atuais.
3. Atualiza docstrings explicando o novo parâmetro.
> [infra] Melhora output das funções list_* e get_* na API do Python

- docs/colab_data.md
- python-package/basedosdados/__init__.py
- python-package/basedosdados/constants.py
- python-package/basedosdados/upload/base.py
Duplicata de #537 
**Sua solicitação de recurso está relacionada a um problema? Por favor, descreva.**
Em certos ambientes, como _jobs_ lançadas pelo `K8sRunLauncher` do Dagster, não é possível (até o momento) montar volumes nos containers e nem é viável acessá-los para realizar a configuração do basedosdados. No entanto, ainda é possível configurar variáveis de ambiente, o que poderia permitir a configuração do basedosdados.
**Descreva a solução que você gostaria**
A implementação aqui submetida parte de uma configuração já realizada do basedosdados em uma máquina qualquer. Sendo assim, para gerar as variáveis de ambiente para os containers pode-se fazer:
```sh
export BASEDOSDADOS_CONFIG=$(cat ~/.basedosdados/config.toml | base64)
export BASEDOSDADOS_CREDENTIALS_PROD=$(cat …
```
> [infra] Configurar o basedosdados a partir de variáveis de ambiente

- python-package/basedosdados/download/download.py
- python-package/basedosdados/exceptions.py
- python-package/basedosdados/upload/table.py
- python-package/basedosdados/validation/exceptions.py
- python-package/tests/test_download.py
- python-package/tests/test_table.py
*  PR #580 
* Issue #519 
Este PR corrige o traceback das funções `download`, `read_sql` e `read_table` e adiciona testes que verificam se cada erro específico está associado ao traceback correto. Como sugerido por @JoaoCarabetta [aqui](https://github.com/basedosdados/mais/issues/519#issuecomment-882939665), dei preferência às exceções do `pandas-gbq`.
* Corrige ordem do bloco `try`/`except` em `read_sql`, colocando as exceções mais específicas primeiro. As mais genéricas estavam no começo, impedindo que as mais específicas aparecessem. 
* Isola teste do caso da não especificação de `billing_project_id`
* Adiciona testes para os seguintes erros:
* `billing_project_id` especificado, porém inválido
* query inválida: projeto inexistente
* query inválida: dataset inexistente …
> [infra] Adiciona testes e corrige o traceback da função `download`

- .github/workflows/table-approve/table_approve.py
Quando os metadados de uma tabela são publicados no CKAN via `table-approve`, é preciso checar, antes, se os metadados do dataset correspondentes já existem no CKAN. Este PR adiciona esse passo a mais e a publicação do dataset caso ele ainda não exista no CKAN, consertando o passo de metadados da `table-approve`.
> [infra] Conserta passo de publicação dos metadados na Action `table-approve`

- python-package/requirements-dev.txt
Atualiza dependências do ambiente dev de Python usado pela Action `build-docs`, resolvendo o issue #974.
> [infra] Conserta dependência do `mkdocs` no `requirements-dev.txt`

- .github/workflows/table-approve.yml
- .github/workflows/table-approve/table_approve.py
- bases/test_dataset/dataset_config.yaml
- bases/test_dataset/test_table/table_config.yaml
- python-package/tests/test_metadata.py
Este PR recria o #981, na tentativa de debuggar a action `table-approve` e consertar seu passo de publicação de metadados.
- Fazer o `table-approve` commitar os YAMLs atualizados pós-publicação de metadados
> [infra] Conserta passo de publicação dos metadados na action `table-approve` [2]

- bases/br_me_rais/microdados_vinculos/table_config.yaml
PR novo para re-rodar a action do `table approve` para `microdados_vinculos` que falhou no PR #1001.
> [dados-fix] `br_me_rais`: Update table_config.yaml

- python-package/basedosdados/download/base.py
- python-package/pyproject.toml
Conforme reportado nos testes, o módulo ``google.colab`` só pode ser importado quando estiver no ambiente do ``colab``, nunca localmente. Refiz a importação para que ela não ocorra localmente.
> Colab authentication

- python-package/basedosdados/cli/cli.py
Parâmetro  `job_config_params` foi removido do método mas não da cli
> [infra] removing parameter job_config_params from cli

- python-package/basedosdados/cli/cli.py
- python-package/basedosdados/upload/table.py
Hoje ao utilizar o `Table.create` não se tem a opção de ignorar os metadados do ckan e gerar um novo `table_config.yaml` a partir do arquivo local. No entando essa feature já existe para o `Metadata.create`, expor o parametro `force_columns` no `Table.create` pode ser uma solução
> [infra] expoe parametro para gerar `table_config.yaml` a partir dos dados locais

- docs/docs/access_data_bq.md
- docs/mkdocs.yml
* [ccadd59](https://github.com/basedosdados/mais/pull/1730/commits/ccadd591dd1db615553e0487e1d5f3738c1d1292), [06f7a51](https://github.com/basedosdados/mais/pull/1730/commits/06f7a5180c883198fa94a983aae4902a25c46c73): Pedido do Hidelbrando pelo grupo do whatsapp, estava com dificuldade de fixar o projeto pois a nomenclatura do BQ mudou!
* [ebab189](https://github.com/basedosdados/mais/pull/1730/commits/ebab189f4b386ac1be46802c32c6e7413e9a5171): Aproveitei para corrigir tb a opção de edição de página, que estava com o link quebrado quando clica no botão de Editar (print abaixo). https://github.com/mkdocs/mkdocs/issues/1321
> [docs] Atualiza instrução para fixar projeto no BQ

- python-package/basedosdados/download/download.py
Introduzido em https://github.com/basedosdados/mais/pull/1712. A função foi removida
Reproduzindo:
```
cd /tmp
mkdir bd-beta-21
cd bd-beta-21
```
```
python -m venv .venv
source .venv/bin/activate
python -m pip install "basedosdados[upload]==2.0.0b21"
```
```
python --version                                      
Python 3.9.17
```
```
touch test.py
```
`test.py`:
```python
import basedosdados as bd
df = bd.read_sql(
"select * from `basedosdados-dev.br_inep_saeb_staging.dicionario`",
billing_project_id="basedosdados-dev",
)
print(df)
```
`python test.py`
```
Traceback (most recent call last):
File "/tmp/bd-beta-21/test.py", line 3, in <module>
df = bd.read_sql(
File "/tmp/bd-beta-21/.venv/lib/python3.9/site-packages/basedosdados/download/download.py", line 57, in read_sql …
```
> fix `_set_config_variables` is not defined

- .github/scripts/setup-config.py
- .github/workflows/ci-python.yml
Precisamos de uma secret `GOOGLE_CREDENTIALS` com a chave da conta de serviço para executar os testes.
> Tests: add setup config ci

- python-package/basedosdados/backend.py
Esses dois parâmetros estavam presente na versão beta 5. Foi removido por algum motivo impossibilitando fazer mutações já que não podemos passar o username e password no header para pegar o token
Em pipelines usamos para atualizar os metadados https://github.com/basedosdados/pipelines/blob/ad1656be51e3502bb4d6afbf6b48627c1eeac5a7/pipelines/utils/metadata/utils.py#L423
> backend: add headers and client param
